/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:97090c73-7959-4a7c-b92e-1ec8d0458130",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_l2HIVx6A2",
    "aws_user_pools_web_client_id": "gfjpbomeqbj9s6vcd2lq29han",
    "oauth": {}
};


export default awsmobile;
